name: Bug report
description: Create an issue to help us improve
title: "[Bug]: "
labels: ["bug"]
type: "Bug"
body:
  - type: markdown
    attributes:
      value: |
        Please provide all the necessary information to expedite the response.
  - type: textarea
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: input
    attributes:
      label: Software Version
      description: Software version, branch, or tag in the DLStreamer Repository
      placeholder: v2026.0.0 / main branch
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Operating System
      description: What OS are you using?
      options:
        - Ubuntu 22.04 (LTS)
        - Ubuntu 24.04 (LTS)
        - Windows 11
        - Other (Please specify in description)
    validations:
      required: true

  - type: textarea
    attributes:
      label: System Setup
      description: Describe your system and software setup. Include any critical video, audio, and model files.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Reproducible Steps
      description: Describe how we can reproduce your issue.
    validations:
      required: true
